### ISSUE TITLE
RuntimeException in BaseApi class

### ISSUE THREAD

**Issue by FMestric** [StroeerSE/StroeerBeaconSDK_Android#5]
After the implementation of the Stroeer Proxity SDK we seem to be getting crashes caused by a RuntimeException in the BaseApi class. Message we are getting is `Caused by java.lang.RuntimeException: Method with name setForegroundNotification not found` but we cannot find a reference to such method in the implementation documentation.

Stack traces are attached.
[RuntimeException_1.txt](https://github.com/StroeerSE/StroeerBeaconSDK_Android/files/1337707/RuntimeException_1.txt)
[RuntimeException_2.txt](https://github.com/StroeerSE/StroeerBeaconSDK_Android/files/1337708/RuntimeException_2.txt)

**Comment by swendrich** [comment]
Hi Filip,
thanks for your report. Were you able to dive deeper into it? Is there a way to reproduce the bug?

Thanks a lot, Sebastian

**Comment by FMestric** [comment]
Unfortunately no, we have not. The build with the included SDK was only distributed to a handful of beta users.
What I can do is share our Crashlytics reports for the issues so they may perhaps give you some more insight into this.

http://crashes.to/s/a0212f3cc14
http://crashes.to/s/e4472a33455

**Comment by FMestric** [comment]
Seems we got another crash that is related to the Proxity SDK: http://crashes.to/s/802d249a0d7

One thing that comes to mind is that we are missing some -keep lines of code in the proguard-rules.pro of our project. Is there a custom -keep that we should add for the SDK to function properly?

**Comment by Favendo** [comment]
We were able to reproduce the bug @FMestric has reported. The runtime exception is caused by using proguard to obfuscate the android source code. If you add the following keep statements
-keep class de.stroeer.** { *; }
-keep class org.eclipse.paho.** { *; }
in your proguard-rules.pro file then the error should no longer occur.
